### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by mdibaiee** [muzix/ghost-s3#16]
Hey,

I've setup `ghost-s3` as suggested in README, like this:

```
config: {
  production: {
    storage: {
        active: 'ghost-s3',
        'ghost-s3': {
          accessIdKey: process.env.S3_ACCESS,
          secretAccessKey: process.env.S3_SECRET,
          bucket: process.env.S3_BUCKET,
          region: process.env.S3_REGION,
          assetHost: process.env.S3_HOST
        }
     }
  }
}
```

The credentials are filled correctly (I logged it, the values are correct), but I get this:

```
2015-12-26T11:29:20.607307+00:00 app[web.1]:   message: 'Missing credentials in config',
2015-12-26T11:29:20.607308+00:00 app[web.1]:   code: 'CredentialsError',
2015-12-26T11:29:20.607309+00:00 app[web.1]:   errno: 'ECONNREFUSED',
2015-12-26T11:29:20.607309+00:00 app[web.1]:   syscall: 'connect',
2015-12-26T11:29:20.607310+00:00 app[web.1]:   address: '169.254.169.254',
2015-12-26T11:29:20.607310+00:00 app[web.1]:   port: 80,
2015-12-26T11:29:20.607311+00:00 app[web.1]:   time: Sat Dec 26 2015 11:29:20 GMT+0000 (UTC),
2015-12-26T11:29:20.607311+00:00 app[web.1]:   originalError:
2015-12-26T11:29:20.607312+00:00 app[web.1]:    { message: 'Could not load credentials from any providers',
2015-12-26T11:29:20.607312+00:00 app[web.1]:      code: 'CredentialsError',
2015-12-26T11:29:20.607313+00:00 app[web.1]:      errno: 'ECONNREFUSED',
2015-12-26T11:29:20.607314+00:00 app[web.1]:      syscall: 'connect',
2015-12-26T11:29:20.607314+00:00 app[web.1]:      address: '169.254.169.254',
2015-12-26T11:29:20.607315+00:00 app[web.1]:      port: 80,
2015-12-26T11:29:20.607315+00:00 app[web.1]:      time: Sat Dec 26 2015 11:29:20 GMT+0000 (UTC),
2015-12-26T11:29:20.607316+00:00 app[web.1]:      originalError:
2015-12-26T11:29:20.610862+00:00 app[web.1]:  Error: connect ECONNREFUSED 169.254.169.254:80
2015-12-26T11:29:20.607316+00:00 app[web.1]:       { code: 'ECONNREFUSED',
2015-12-26T11:29:20.610861+00:00 app[web.1]: ERROR: Missing credentials in config
2015-12-26T11:29:20.610862+00:00 app[web.1]:
2015-12-26T11:29:20.607317+00:00 app[web.1]:         errno: 'ECONNREFUSED',
2015-12-26T11:29:20.610863+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:897:20)
2015-12-26T11:29:20.607318+00:00 app[web.1]:         address: '169.254.169.254',
2015-12-26T11:29:20.610864+00:00 app[web.1]:
2015-12-26T11:29:20.607317+00:00 app[web.1]:         syscall: 'connect',
2015-12-26T11:29:20.610864+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-26T11:29:20.607318+00:00 app[web.1]:         port: 80,
2015-12-26T11:29:20.611888+00:00 app[web.1]: 107.6.181.239 - - [26/Dec/2015:11:29:20 +0000] "POST /ghost/api/v0.1/uploads/ HTTP/1.1" CredentialsError 90 "http://betternet-web.herokuapp.com/blog/ghost/editor/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0"
2015-12-26T11:29:20.610860+00:00 app[web.1]:
2015-12-26T11:29:20.607319+00:00 app[web.1]:         message: 'connect ECONNREFUSED 169.254.169.254:80' } } }
2015-12-26T11:29:20.610863+00:00 app[web.1]:     at Object.exports._errnoException (util.js:874:11
```

Any idea on what's happening? Thanks

**Comment by mdibaiee** [comment]
Argh, that's `accessKeyId`, not `accessIdKey`, sorry. :hammer:
