### ISSUE TITLE
Not working after an upgrade to ghost-0.10.1

### ISSUE THREAD

**Issue by lyn5466** [muzix/ghost-s3#21]
Excuse me. This package works perfect before I did an upgrade to ghost-0.10.1. Now, I got the following error. Could anyone help me? By the way, I built my ghost on Heroku.

```
start /app
> node index

Migrations: Creating database backup

ERROR: Your storage adapter does not inherit from the Storage Base. 

 Error
    at Error.IncorrectUsage (/app/core/server/errors/
    at Object.getStorage (/app/core/server/storage/index.js:54:15)
    at setupMiddleware (/app/core/server/middleware/index.js:126:44)
    at /app/core/server/index.js:131:9
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/
    at Promise._fulfill (/app/node_modules/bluebird/js/release/
    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/
    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/
    at Async._drainQueue (/app/node_modules/bluebird/js/release/
    at Async._drainQueues (/app/node_modules/bluebird/js/release/
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules
    at processImmediate [as _immediateCallback] (timers.js:383:17) 
 State changed from starting to crashed
```

**Comment by matitalatina** [comment]
There are some [breaking changes](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module) in 0.10.0 for custom storage module.
This repo should be updated in order to work on 0.10.0

**Comment by pascalandy** [comment]
I was scared about this.
Is this project still maintained ? Will stay on Ghost 0.9 for now.

Thanks!

**Comment by sunkaflek** [comment]
Same problem. This worked for me: https://github.com/aorcsik/ghost-s3-storage-adapter

**Comment by pascalandy** [comment]
Seriously @snakeyak !? OK I guess something is wrong in my setup ... grhhh. 
Thanks for letting me know.

**Comment by sunkaflek** [comment]
@pascalandy I did remove the ghost peer dependency from its package.json, and removed the npm-shrinkwrap.json in ghost itself. Don't know if both are necessary, but it's how I got to a working ghost on heroku :) Hope that helps

**Comment by ZiiX** [comment]
Can someone help me figure out how to change the hard-coded credential check against amazon? I used my custom bucket domain but it still wants to ping amazon. I'm using minio.io as my storage. It's s3 compatible & the credentials work elsewhere s3 credentials are used. Thanks so much for your time! I tried the ghost-s3-storage-adapter one too and it doesn't work.
